# Generated by Django 6.0.3 on 2026-06-04 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_course_courses_cou_owner_i_d9dd44_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10)),
                ('quiz_count', models.PositiveSmallIntegerField(default=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='quiz_game_l_number_cced56_idx'), models.Index(fields=['difficulty'], name='quiz_game_l_difficu_199c28_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_levels', models.ManyToManyField(blank=True, related_name='completed_in_progress', to='quiz_game.level')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game_progresses', to='courses.course')),
                ('unlocked_levels', models.ManyToManyField(blank=True, related_name='unlocked_in_progress', to='quiz_game.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_game_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('passed', 'Validé'), ('failed', 'Échoué')], default='pending', max_length=15)),
                ('completed_quiz_count', models.PositiveSmallIntegerField(default=0)),
                ('required_quiz_count', models.PositiveSmallIntegerField(default=5)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progresses', to='quiz_game.level')),
                ('user_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_progresses', to='quiz_game.quizgameprogress')),
            ],
            options={
                'ordering': ['level__number'],
            },
        ),
        migrations.AddIndex(
            model_name='quizgameprogress',
            index=models.Index(fields=['user', 'course'], name='quiz_game_q_user_id_aa47d2_idx'),
        ),
        migrations.AddIndex(
            model_name='quizgameprogress',
            index=models.Index(fields=['course', 'topic'], name='quiz_game_q_course__b9ff27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quizgameprogress',
            unique_together={('user', 'course', 'topic')},
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['user_progress', 'level'], name='quiz_game_l_user_pr_4880bb_idx'),
        ),
        migrations.AddIndex(
            model_name='levelprogress',
            index=models.Index(fields=['status'], name='quiz_game_l_status_3f4d01_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='levelprogress',
            unique_together={('user_progress', 'level')},
        ),
    ]
