# Generated by Django 6.0.3 on 2026-06-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelprogress',
            name='generated_questions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='levelprogress',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('ready', 'Prêt'), ('in_progress', 'En cours'), ('passed', 'Validé'), ('failed', 'Échoué')], default='pending', max_length=15),
        ),
    ]
