# Generated by Django 6.0.3 on 2026-06-23 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_game', '0003_gamequestion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gamequestion',
            new_name='quiz_game_g_level_p_41b538_idx',
            old_name='quiz_game_g_level_p_idx',
        ),
    ]
