# Generated by Django 6.0.3 on 2026-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
