# Generated by Django 6.0.3 on 2026-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_owner_i_d9dd44_idx_and_more'),
        ('quizz', '0002_quiz_status_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', 'status'], name='quizz_quiz_course__fed8b9_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['course', '-created_at'], name='quizz_quiz_course__e222bf_idx'),
        ),
    ]
