# Generated by Django 6.0.3 on 2026-06-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0003_quiz_quizz_quiz_course__fed8b9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('in_progress', 'En cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='pending', max_length=15),
        ),
    ]
