# Generated by Django 6.0.3 on 2026-04-07 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_coursechunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', 'status'], name='courses_cou_owner_i_d9dd44_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', '-created_at'], name='courses_cou_owner_i_e2e8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='courses_cou_status_158bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='coursechunk',
            index=models.Index(fields=['course', 'chunk_index'], name='courses_cou_course__97491b_idx'),
        ),
    ]
