# Generated by Django 6.0.3 on 2026-06-23 20:44

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_owner_i_d9dd44_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384, null=True),
        ),
    ]
