"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config
from .app_config import COURSE_UPLOAD_RATE, GENERATION_RATE

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# ─── Sécurité ─────────────────────────────────────────────
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY') # Récupère la clé secrète à partir de la variable d'environnement

# settings.py
GEMINI_API_KEY = config('GEMINI_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool) # Récupère le mode debug à partir de la variable d'environnement (par défaut False)

ALLOWED_HOSTS = ['localhost', '127.0.0.1',]


# ─── Applications installées ──────────────────────────────────
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Packages tiers
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    #'django_celery_results',
    'django_extensions',

    # Nos applications
    'users',
    'courses',
    'quizz',
    'flashcards',

    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Permet de gérer les requêtes CORS (Cross-Origin Resource Sharing) pour autoriser les requêtes provenant de domaines différents
    'django.middleware.security.SecurityMiddleware', # Fournit plusieurs fonctionnalités de sécurité pour protéger l'application contre les attaques courantes (ex: clickjacking, XSS, etc.)
    'django.contrib.sessions.middleware.SessionMiddleware', # Gère les sessions utilisateur en stockant les données de session dans des cookies ou dans la base de données
    'django.middleware.common.CommonMiddleware', # Fournit plusieurs fonctionnalités de base pour gérer les requêtes HTTP (ex: redirections, gestion des en-têtes, etc.)
    'django.middleware.csrf.CsrfViewMiddleware', # Protège contre les attaques CSRF (Cross-Site Request Forgery) en vérifiant que les requêtes POST proviennent du même domaine
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Gère l'authentification des utilisateurs en associant les requêtes à des utilisateurs authentifiés
    'django.contrib.messages.middleware.MessageMiddleware', # Permet d'afficher des messages de feedback à l'utilisateur (ex: messages.success, messages.error, etc.)
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Protège contre les attaques de clickjacking en empêchant l'affichage de l'application dans des iframes provenant de domaines différents
]

ROOT_URLCONF = 'config.urls' # Spécifie le module de configuration des URLs racines du projet (config/urls.py)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates', # Utilise le moteur de template Django
        'DIRS': [], # Permet de spécifier des dossiers supplémentaires pour les templates (en plus des dossiers "templates" de chaque application)
        'APP_DIRS': True, # Permet à Django de chercher les templates dans les dossiers "templates" de chaque application
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Affiche les erreurs de template dans le navigateur
                'django.template.context_processors.request', # Permet d'accéder à l'objet request dans les templates
                'django.contrib.auth.context_processors.auth', # Ajoute les variables d'authentification (user, perms) dans les templates
                'django.contrib.messages.context_processors.messages', # Permet d'afficher les messages de Django (ex: messages.success) dans les templates
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application' # Spécifie le module de configuration WSGI pour le projet (config/wsgi.py)


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql', # Utilise le backend PostgreSQL pour la base de données
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# ─── Modèle utilisateur personnalisé ─────────────────
AUTH_USER_MODEL = 'users.CustomUser' # Spécifie le modèle utilisateur personnalisé à utiliser pour l'authentification (users/models.py)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', # Vérifie que le mot de passe n'est pas trop similaire aux attributs de l'utilisateur (ex: nom, email, etc.)
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', # Vérifie que le mot de passe a une longueur minimale
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', # Vérifie que le mot de passe n'est pas un mot de passe courant
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', # Vérifie que le mot de passe n'est pas entièrement numérique
    },
        
]


# ─── DRF + JWT ───────────────────────────────────────
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'course_upload': COURSE_UPLOAD_RATE,
        'generation': GENERATION_RATE,
    },
    'DEFAULT_PAGINATION_CLASS': 'config.pagination.StandardPagination',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1), # Définit la durée de vie des tokens d'accès à 1 heure (après quoi l'utilisateur devra se reconnecter ou utiliser un refresh token pour obtenir un nouveau token d'accès)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7), # Définit la durée de vie des tokens de rafraîchissement à 7 jours (après quoi l'utilisateur devra se reconnecter pour obtenir de nouveaux tokens)
    'ROTATE_REFRESH_TOKENS': True,  # nouveau refresh token à chaque refresh
    'BLACKLIST_AFTER_ROTATION': True, # blacklist le refresh token précédent après rotation
    'AUTH_HEADER_TYPES': ('Bearer',), # Spécifie que les tokens JWT doivent être envoyés dans l'en-tête Authorization
}

# ─── CORS (autorise React à appeler l'API) ────────────
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',    # ← Vite
    'http://127.0.0.1:5173',   # ← Vite
    #'https://c847-154-72-153-3.ngrok-free.app', # ← tunnel pour Vite
]
# Important pour que Django accepte les requêtes via un proxy/tunnel
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr' # Spécifie la langue par défaut pour l'application (fr-fr pour le français de France)

TIME_ZONE = 'UTC'

USE_I18N = True # Active la prise en charge de l'internationalisation (i18n) pour permettre la traduction de l'application dans différentes langues

USE_TZ = True # Active la prise en charge des fuseaux horaires pour permettre la gestion correcte des dates et heures dans différentes régions du monde


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ─── Fichiers statiques & médias ─────────────────────
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # les PDF/images uploadés ici


# ─── Celery ───────────────────────────────────────────
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # Redis comme boîte aux lettres
CELERY_RESULT_BACKEND = 'django-db'             # Résultats stockés en PostgreSQL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# ─── django-celery-results ────────────────────────────
INSTALLED_APPS += ['django_celery_results']

os.environ['HF_TOKEN'] = config('HF_TOKEN', default='')

# settings.py

from kombu import Queue

# ─── Queues Celery ────────────────────────────────────
CELERY_TASK_QUEUES = (
    Queue('courses'),     # OCR, embeddings (CPU intensif)
    Queue('generation'),  # Quiz, Flashcards (I/O intensif)
)
CELERY_TASK_DEFAULT_QUEUE = 'generation'

# ─── Concurrence ──────────────────────────────────────
CELERY_WORKER_PREFETCH_MULTIPLIER = 5  # chaque worker prend 5 tâche à la fois
CELERY_TASK_ACKS_LATE             = True  # confirme la tâche après exécution

# ─── Logging structuré ────────────────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'celery_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'celery.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console', 'celery_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'courses': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'flashcards': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'quizz': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ─── Cache Redis ──────────────────────────────────────
# Pour développement local : utilise cache en mémoire par défaut
# Pour production avec Redis : configure CACHE_REDIS_ENABLED=true
USE_REDIS_CACHE = config('CACHE_REDIS_ENABLED', default=False, cast=bool)

if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': config('REDIS_URL', default='redis://127.0.0.1:6379/1'),
        }
    }
else:
    # Cache en mémoire pour développement local
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# ─── Sentry (monitoring erreurs) ──────────────────────
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.celery import CeleryIntegration

sentry_sdk.init(
    dsn=config('SENTRY_DSN', default=None),
    integrations=[
        DjangoIntegration(),
        CeleryIntegration(),
    ],
    traces_sample_rate=0.1,  # 10% des requêtes tracées
    send_default_pii=False,  # Pas de données personnelles
    environment=config('ENVIRONMENT', default='development'),
)
