# Generated by Django 6.0.3 on 2026-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcarddeck',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('generating', 'Génération en cours'), ('ready', 'Prêt'), ('failed', 'Échec')], default='pending', max_length=15),
        ),
    ]
