# Generated by Django 6.0.3 on 2026-04-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_courses_cou_owner_i_d9dd44_idx_and_more'),
        ('flashcards', '0002_flashcarddeck_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['course', 'status'], name='flashcards__course__fe5a42_idx'),
        ),
        migrations.AddIndex(
            model_name='flashcarddeck',
            index=models.Index(fields=['course', '-created_at'], name='flashcards__course__333f4a_idx'),
        ),
    ]
